#!/bin/bash
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
command_file="$repo_root/commands/autonomous-review.md"

grep -F -- '/aidd:autonomous-review [対象] [--base <branch>] [--head <branch>] [--reviewer codex|claude]' "$command_file"
grep -F -- '--reviewer codex|claude' "$command_file"
grep -F -- '未指定時の既定値は `codex`' "$command_file"
grep -F -- '--reviewer claude' "$command_file"
grep -F -- '同一モデルによる自己レビュー' "$command_file"
grep -F -- '最終判定は常に `human_required`' "$command_file"
grep -F -- '--head <branch>' "$command_file"
grep -F -- 'git diff' "$command_file"
grep -F -- '<base>...HEAD' "$command_file"
grep -F -- '<base>...<head>' "$command_file"
grep -F -- 'git worktree add --detach' "$command_file"
grep -F -- '現在の作業ツリーを変更してはならない' "$command_file"
grep -F -- '--base` と `--head` は対で指定する' "$command_file"
grep -F -- 'AskUserQuestion' "$command_file"
grep -F -- '未指定を理由に終了せず' "$command_file"
grep -F -- 'git check-ref-format --branch <branch>' "$command_file"
grep -F -- '--end-of-options <branch>^{commit}' "$command_file"
grep -F -- '対象外の変更が混ざる場合、レビューを始めずに停止' "$command_file"
grep -F -- 'codex exec --sandbox read-only' "$command_file"
grep -F -- 'human_required' "$command_file"
grep -F -- '同一モデルの自己レビューへ黙ってフォールバックしてはならない' "$command_file"
grep -F -- '"verdict": "approved" | "changes_requested"' "$command_file"
grep -F -- 'JSON以外の出力' "$command_file"
grep -F -- '最大3ラウンド' "$command_file"
grep -F -- 'aidd:refuter' "$command_file"
grep -F -- '.aidd/review-dismissed.md' "$command_file"
grep -F -- 'build / lint / format / typecheck / test' "$command_file"
grep -F -- 'ShellCheck' "$command_file"
grep -F -- 'Hadolint' "$command_file"
grep -F -- 'auto_merge_eligible' "$command_file"
grep -F -- '外部公開APIの破壊的変更' "$command_file"
grep -F -- '.aidd/autonomous-review/' "$command_file"
grep -F -- 'state.json' "$command_file"
grep -F -- 'report.md' "$command_file"
grep -F -- 'git push' "$command_file"
grep -F -- 'gh pr create' "$command_file"
grep -F -- 'レビュー出力を `eval`・`source`・コマンド置換で実行してはならない' "$command_file"
grep -F -- 'perspective_reviews' "$command_file"
grep -F -- '観点別レビューを追加で実行' "$command_file"
grep -F -- 'aidd:security-reviewer' "$command_file"
grep -F -- '`approved` を返したことは、網羅的にレビューされたことを意味しない' "$command_file"
grep -F -- '該当する観点別レビューの完了' "$command_file"
grep -F -- 'state.json のスキーマ' "$command_file"
grep -F -- 'schema_version' "$command_file"
grep -F -- '同じ概念に別名を作らない' "$command_file"
grep -F -- '必須キーを欠く、または値域外の状態を書こうとした場合は `failed` とする' "$command_file"
grep -F -- '件数だけの要約に置き換えてはならない' "$command_file"
grep -F -- 'deferred の追跡' "$command_file"
grep -F -- '"type": "unresolved"' "$command_file"
grep -F -- '`tracking` が `unresolved` の `deferred` なし' "$command_file"
grep -F -- '< /dev/null' "$command_file"
grep -F -- 'exit 0 で空の応答' "$command_file"
grep -F -- '終了コードでも stderr の有無でも成否を判断しない' "$command_file"
grep -F -- ':(exclude).aidd' "$command_file"
grep -F -- '--skip-git-repo-check -C <snapshot-dir>' "$command_file"
grep -F -- 'git apply' "$command_file"
grep -F -- '`rounds[].snapshot`' "$command_file"
grep -F -- '5 の現物検証が終わった時点で削除する' "$command_file"
grep -F -- '変更前ではなく変更後の内容で確かめる' "$command_file"
grep -F -- 'Bash ツールの `timeout` パラメータ' "$command_file"
grep -F -- 'codex login status < /dev/null' "$command_file"
grep -F -- '--output-last-message' "$command_file"
grep -F -- '`proceeding` を含む警告は失敗ではない' "$command_file"
grep -F -- '現行は `2`' "$command_file"
if grep -F -- 'git worktree remove --force' "$command_file"; then
  echo "codex must not run from a git worktree: the shared object store still exposes .aidd/" >&2
  exit 1
fi
grep -F -- '拡張子は `.txt`' "$command_file"
