#!/bin/bash
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
design_review="$repo_root/commands/design-review.md"
reviewer="$repo_root/agents/reviewer.md"
refuter="$repo_root/agents/refuter.md"
eval_command="$repo_root/commands/eval.md"
review_loop="$repo_root/skills/review-loop/SKILL.md"
adr_command="$repo_root/commands/adr.md"

grep -F -- '--depth=standard|deep' "$design_review"
grep -F -- '既定は `--depth=standard`' "$design_review"
grep -F -- '`--depth=deep`' "$design_review"
grep -F -- 'high/mid がなければ refuter を起動しない' "$design_review"
grep -F -- 'standard では反証後の high/mid を直接報告する' "$design_review"
grep -F -- '指摘なしの場合は' "$reviewer"
grep -F -- '1行だけ' "$reviewer"
grep -F -- '引用箇所と必要最小限の関連パス' "$refuter"
grep -F -- '`--depth=deep`' "$eval_command"
grep -F -- '--review-delta' "$design_review"
grep -F -- '差分と必要な周辺文脈' "$design_review"
grep -F -- '全体再レビュー' "$design_review"
grep -F -- '初回を含めて最大3ラウンド' "$review_loop"
grep -F -- 'deferred mid' "$review_loop"
grep -F -- '`/aidd:issue-split`' "$review_loop"
grep -F -- '`.aidd/review-dismissed.md` への理由つき追記' "$review_loop"
grep -F -- '追跡先が確定しない指摘は `deferred mid` にできず' "$review_loop"
grep -F -- '全ソースの最大番号 +1' "$adr_command"
grep -F -- 'git ls-tree -r --name-only origin/HEAD -- docs/adr/' "$adr_command"
grep -F -- 'refs/remotes/origin/' "$adr_command"
grep -F -- '検討した代替案' "$adr_command"
